backend/accounts/urls.py
from django.urls import path
from accounts.views.views import register, profile, logout_view, login_view, edit_profile_view, confirm_email
from django.contrib.auth import views as auth_views

app_name = "shop"

urlpatterns = [
    path('register/', register, name="register"),
    path('profile/', profile, name="profile"),
    path('edit_profile/', edit_profile_view, name="edit_profile_view"),
    path('logout/', logout_view, name="logout"),
    path("login/", login_view, name="login"),
    path("confirm_email/", confirm_email, name="confirm_email"),
    path("password_reset/", auth_views.PasswordResetView.as_view(
        template_name="password_reset/form.html", email_template_name="password_reset/email.html", success_url="done/"
    ), name="password_reset"),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(
        template_name="password_reset/done.html"
    ), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name="password_reset/confirm.html"
    ), name="password_reset_confirm"),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(
        template_name="password_reset/complete.html"
    ), name="password_reset_complete")
]

backend/catalog/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from . import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("products.urls", namespace="products")),
    path('accounts/', include('accounts.urls',  namespace="accounts")),
    path("captcha/", include("captcha.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
        path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
        path('api/token/', TokenObtainPairView.as_view(), name="token-obtain-pair"),
        path('api/token/refresh/', TokenObtainPairView.as_view(), name="token-refresh")
    ]

backend/products/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter


from .views.category import CategoryViewSet
from .views.product import ProductViewSet
from .views.cart import CartViewSet

from .views.views import index, about, products_details, cart_add, delete_item_cart, checkout, cart_detail
from accounts.views.accounts import AccountViewSet

app_name = "products"

router = DefaultRouter()

router.register(r"products", viewset=ProductViewSet, basename="products")
router.register(r"categories", viewset=CategoryViewSet, basename="categories")
router.register(r"carts", viewset=CartViewSet, basename="carts")

urlpatterns = [
    path('index/', index, name="index") ,
    path('about/', about, name="about"),
    path('products/<int:product_id>/', products_details, name="products_details"),
    path("cart_add/<int:product_id>/", cart_add, name="cart_add"),
    path("products_details/", products_details, name="products_details"),
    path("delete_item_cart/", delete_item_cart, name="delete_item_cart"),
    path("checkout/", checkout, name="checkout"),
    path("cart_detail/", cart_detail, name="cart_detail"),
    path("captcha/", include("captcha.urls")),
    path("accounts/", include("accounts.urls"))
]

urlpatterns += router.urls

backend/products/forms.py
from django import forms
from .models import Order
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class OrderCreateForm(forms.ModelForm):
    payment_method = forms.ChoiceField(choices={"liqpay": "With LiqPay",
                                                "monopay": "With MonoPay",
                                                "googlepay": "With Google Pay",
                                                "cash": "With Cash"
                                                }
                                       )
    class Meta:
        model = Order
        fields = ["contact_name", "contact_email", "contact_phone", "address"]
        labels = {"contact_name": "Your name",
                  "contact_email": "Your email",
                  "contact_phone": "Your phone",
                  "address": "Your address",
                  "payment_method": "Payment method"
                  }

backend/products/views/cart.py
from django.conf import settings
from django.shortcuts import get_object_or_404
from rest_framework.viewsets import ReadOnlyModelViewSet, ViewSet
from rest_framework.response import Response
from rest_framework.decorators import action
from products.models import Cart, CartItem, Product, OrderItem, Payment, Order
from products.serializers.cart_serializer import CartItemSerializer, CartSerializer
from products.serializers.product_serializer import ProductSerializer
from utils.email import send_order_confirmation_email
from products.forms import OrderCreateForm


class CartViewSet(ViewSet):
    @action(detail=False, methods=["post"], url_path="add-product")
    def add(self, request, product_id=None):
        product = get_object_or_404(Product, id=product_id)
        if request.user.is_authenticated:
            cart = request.user.cart
            cart_item, created = CartItem.objects.get_or_create(
                product=product, cart=cart
            )
            if created:
                cart_item.amount = 1
            else:
                cart_item.amount += 1
            cart_item.save()
        else:
            cart = request.session.get(settings.CART_SESSION_ID, default={})
            cart[str(product_id)] = cart.get(str(product_id), default=0) + 1
        return Response({"message": f"Product with id {product_id} added"}, status=200)

    @action(detail=False, methods=["get"], url_path="get-cart-items")
    def items(self, request):
        if request.user.is_authenticated:
            cart = request.user.cart
            return Response(CartItemSerializer(cart).data)
        else:
            cart = request.session.get(settings.CART_SESSION_ID, default={})
            products = Product.objects.filter(id__in=cart.keys())
            items = []
            total = 0
            for product in products:
                data = ProductSerializer(product).data
                amount = cart.get(str(product.id))
                item_total = (product.discount_price or product.price) * amount
                items.append({
                    "product": product,
                    "amount": amount,
                    "item_total": item_total,
                    "cart": None
                })
                total += item_total

            return Response({
                 "user": request.user,
                 "created_at": None,
                 "items": items,
                 "total": total})

    @action(detail=False, methods=["post"], url_path="cart-checkout")
    def checkout(self, request):
        if request.user.is_authenticated:
            cart = request.user.cart
            if not cart or cart.items.count() == 0:
                return Response({"error": "Cart is empty"}, status=400)

        else:
            if not request.session.get(settings.CART_SESSION_ID, default={}):
                return Response({"error": "Cart is empty"}, status=400)

        form = OrderCreateForm(request.data)

        if not form.is_valid():
            return Response({"errors": form.errors}, status=400)

        order = form.save(commit=False)

        if request.user.is_authenticated:
            order.user = request.user

        order.save()

        if request.user.is_authenticated:
            cart_items = order.user.cart.items.select_related("product").all()
            items = OrderItem.objects.bulk_create([
                OrderItem(
                    order=order,
                    product=item.product,
                    amount=item.amount,
                    price=item.discount_price or item.price)
                for item in cart_items])

        else:
            cart_items = order.user.cart.items.select_related("product").all()
            items = OrderItem.objects.bulk_create([
                OrderItem(
                    order=order,
                    product=item["product"],
                    amount=item.amount["amount"],
                    price=item["product"] or item["product"])
                for item in cart_items])

        method = form.cleaned_data["payment_method"]
        total = sum(item.item_total for item in items)

        if method != "cash":
            Payment.objects.create(order=order, provider=method, amount=total)

        else:
            order.status = Order.Status.PROCESSING
            order.save()

        if request.user.is_authenticated:
            request.user.cart.items.all().delete()

        else:
            cart.clear()

        send_order_confirmation_email(order=order)

        return Response({"message": f" Order {order.id} is created"}, status=200)

backend/products/views/category.py
from rest_framework.viewsets import ReadOnlyModelViewSet
from ..models import Category
from ..serializers.category_serializer import CategorySerializers


class CategoryViewSet(ReadOnlyModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializers

backend/products/views/product.py
from rest_framework.viewsets import ModelViewSet
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import OrderingFilter, SearchFilter
from rest_framework.permissions import IsAdminUser, AllowAny
from products.models import Category, Product
from products.serializers.product_serializer import ProductSerializer
from products.filters import ProductFilter


class ProductViewSet(ModelViewSet):
    queryset = Product.objects.select_related("category").all()
    serializer_class = ProductSerializer
    filter_backends = [DjangoFilterBackend, OrderingFilter, SearchFilter]
    filterset_class = ProductFilter
    search_fields = ["name", "description"]
    ordering_fields = ["price", "rating"]

    def get_permissions(self):
        if self.action in ["create", "update", "partial_update", "destroy"]:
            return [IsAdminUser()]
        else:
            return [AllowAny()]

backend/products/views/views.py
from PIL.Image import item
from django.core.checks import messages
from django.shortcuts import render, get_object_or_404, redirect

from ..forms import OrderCreateForm
from ..models import Product, Category, OrderItem, Payment, CartItem, Cart
from django.conf import settings

from utils.email import send_order_confirmation_email


def calculate_discount(value, arg):
    discount_value = value * arg / 100
    return value - discount_value


def index(request):
    product = Product.objects.all()
    categories = Category.objects.all()

    category_name = request.GET.get("category")
    filter_name = request.GET.get("filter")
    product_name = request.GET.get("search")
    min_price = request.GET.get("min_price")
    max_price = request.GET.get("max_price")

    if product_name:
        product = product.filter(name__icontains=product_name)

    if category_name:
        category = Category.objects.get(name=category_name)
        product = product.filter(category=category)

    if min_price:
        product = product.filter(price__gte=min_price)

    if max_price:
        product = product.filter(price__lte=max_price)

    match filter_name:
        case "price_increase":
            products = product.order_by("price")
        case "price_decrease":
            products = product.order_by("-price")
        case "rating_increase":
            products = product.order_by("rating")
        case "rating_decrease":
            products = product.order_by("-rating")

    return render(request, "index.html", context={"product": product, "categories": categories})


def about(request):
    return render(request, "about.html")


def products_details(request, product_id):
    products = get_object_or_404(Product, id=product_id)
    return render(request, "product_details.html", context={"product": products})


def cart_add(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if not request.user.is_authenticated():
        cart = request.session.get(settings.CART_SESSION_ID, {})
        if cart.get(product_id):
            cart[product_id] += 1
        else:
            cart[product_id] = 1
        request.session[settings.CART_SESSION_ID] = cart
    else:
        cart = request.user.cart
        cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
        if not created:
            cart_item.amount += 1
            cart_item.save()
    return redirect("products:cart_detail")


def cart_detail(request):
    if not request.user.is_authenticated():
        cart = request.session.get(settings.CART_SESSION_ID, {})
        product_ids = cart.keys()
        products = Product.objects.filter(id__in=product_ids)
        cart_items = []
        total_price = 0
        for product in products:
            count = cart[str(product.id)]
            if count == 0:
                if product.discount:
                    raw_price = calculate_discount(product.price, product.discount)
                else:
                    raw_price = product.price
            price = count * product.price
            total_price += price
            cart_items.append({"product": products, "count": count, "price": price})

    else:
        try:
            cart = request.user.cart
        except Cart.DoesNotExists:
            cart = None

        if not cart or not cart.items.count():
            cart_items = []
            total_price = 0
        else:
            cart_items = cart.items.select_related("product").all()
            total_price = sum(item.product.price * item.amount for item in cart_items)
        return render(request, "cart_detail.html", context={"cart_items": cart_items, "total_price": total_price})


def delete_item_cart(request, item_id):
    product = get_object_or_404(Product, id=item_id)

    if not request.user.is_authenticated():
        cart = request.session.get(settings.CART_SESSION_ID, {})
        if item_id in cart:
            cart[item_id] -= 1
            request.session[settings.CART_SESSION_ID] = cart
    else:
        try:
            cart = request.user.cart
            item_del = CartItem.objects.get(cart=cart, product=product)
            item_del.delete()
        except CartItem.DoesNotExist:
            cart = None
    return redirect("products:cart_detail")


def checkout(request):
    if (request.user.is_authenticated() and not getattr(request.user, "cart", None)) or (
            not request.user.is_authenticated and not request.session.get(settings.CART_SESSION_ID)
    ):
        messages.error(request, "Cart is empty")
        return redirect("products:cart_detail")

    if request.method == "GET":
        form = OrderCreateForm()
        if request.user.is_authenticated():
            form.initial["contact_email"] = request.user.email
    elif request.method == "POST":
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if request.user.is_authenticated:
                order.user = request.user
            order.save()

            if request.user.is_authenticated:
                cart = getattr(request.user, "cart")
                cart_items = cart.items.select_related("product").all()
            else:
                cart = request.session.get(settings.CART_SESSION_ID)
                cart_items = []
                for product_id, amount in cart.items():
                    product = Product.objects.get(id=product_id)
            cart_items.append({"product": product, "amount": amount})

            items = OrderItem.objects.bulk_create(
                [OrderItem(order=order,
                           product=item.product,
                           amount=item.amount,
                           price=calculate_discount(item.product.price, item.product)
                           )
                 for item in cart_items
                 ]
             )

            total_price = sum(item.product.price * item.amount for item in items)
            method = form.cleaned_data.get("payment_method")
            if method != "cash":
                Payment.objects.create(order=order, provider=method, amount=total_price)
            else:
                order.status = 2

            order.save()

            if request.user.is_authenticated:
                cart.items.all().delete()
            else:
                request.session[settings.CART_SESSION_ID] = {}
            send_order_confirmation_email(order=order)
            messages.success(request, 'Text')
            return redirect('products:index')

    return render(request, "checkout.html", context={"form": form})

backend/products/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>Про нас</h1>
    <p class="lead">Welcome to page!</p>
    <h2>Наша команда </h2>
    <ul>
        <li>
            Oleksandr
        </li>
    </ul>
{% endblock %}

backend/products/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Product {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
</head>
<body class="d-flex flex-column vh-100">
    <header>
        <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
            <div class="container-fluid d-flex flex-wrap justify-content-between align-items-center gap-3">

                <div class="navbar-nav w-100 text-light">
                    <h4><a href="{% url 'products:index' %}" class="navbar-brand text-light">Home</a></h4>
                </div>

                    <div class="nav-item text-light">
                        <form
                            action="{% url 'products:index' %}"
                            method="GET"
                            class="d-flex mx auto">

                        <select name="category" class="form-select me-3" onchange="this.form.submit()">
                            <option value="" {% if not request.GET.category %} selected {% endif %}>Category</option>
                            {% for category in categories %}
                                <option value="{{ category.name }}" {% if request.GET.category == category.name %} selected {% endif %}>{{ category.name }}</option>
                            {% endfor %}
                        </select>

                        <select name="filter" id="form-select me-3" onchange="this.form.submit()" value="{{ request.GET.filter|default:'' }}">
                            <option value="price_increase">{% if not request.GET.filter == price_increase %}  selected {% endif %}>Price Increase</option>
                            <option value="price_decrease">{% if not request.GET.filter == price_decrease %}  selected {% endif %}>Price Decrease</option>
                            <option value="rating_increase">{% if not request.GET.filter == rating_increase %}  selected {% endif %}>Rating Increase</option>
                            <option value="rating_decrease">{% if not request.GET.filter == price_decrease %}  selected {% endif %}>Rating Decrease</option>

                        </select>
                        <input type="search"
                               class="form-control me-3"
                               name="search"
                               placeholder="Пошук товарів"
                               onchange="this.form.submit()"
                               value="{{ request.GET.search|default:'' }}"/>


                        <input
                        type="number"
                        name="min_price"
                        class="w-25 form-control"
                        min="0"
                        onchange="this.form.submit()"
                        value="{{ request.GET.min_price|default:'' }}"
                        />


                        <input
                        type="number"
                        name="max_price"
                        class="w-25 form-control"
                        min="0"
                        onchange="this.form.submit()"
                        value="{{ request.GET.max_price }}">

                        </form>


                        <div class="collapse-navbar-collapse">
                            <ul class="navbar-nav ms-auto">
                        {% if request.user.is_authenticated %}
                                    <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link">Logout</a></li>
                                    <li class="nav-item"><a href="{% url 'accounts:profile' %}" class="nav-link">{{ request.user.username }}</a></li>
                        {% else %}
                                <li class="nav-item"><a href="{% url 'accounts:register' %}" class="navbar-brand text-light">Register</a></li>
                                <li class="nav-item"><a href="{% url 'accounts:login' %}" class="navbar-brand text-light">Login</a></li>
                        {% endif %}
                            </ul>
                        </div>

                        <div>
                            <a href="{% url 'products:cart_detail' %}" type="button" class="btn btn-primary btn-sm"></a>
                            <i class="bi bi-cart"></i> Cart
                        </div>

                    </div>
                </div>
            </nav>

    </header>


    <main class="container mt-5 flex-shrink-0" style="padding-top:50px;;">
        {% block content %}

        {% endblock %}
    </main>

    <footer class="footer mt-5 py-3 px-2 bg-dark fixed-bottom">
        <a href="{% url 'products:about' %}">About Us</a>
    </footer>



</body>
</html>

backend/products/templates/cart_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <h2>Your cart</h2>
        {% if cart_items %}
        <div class="table-responsive">
            <table class="table table-bordered table-haver align-middle text-center">
                <thead class="table-light">
                    <tr>
                        <th>Product</th>
                        <th>Amount</th>
                        <th>Price</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                {% for item in cart_items %}
                    <tr>
                        <td>{{item.product.name}}</td>
                        <td>{{item.amount}}</td>
                        <td>{{item.price}}</td>
                        <td><a href="{% url 'products:cart_delete' item.product.id %}" class="btn btn-sm btn-outline-danger" title="Remove">-</a></td>
                        <td><a href="{% url 'products:cart_add' item.product.id %}" class="btn btn-sm btn-outline-success" title="Add">+</a></td>
                    </tr>
                {% endfor %}
                <tr class="table-secondary">
                    <td class="text-start"><strong>Total:</strong></td>
                    <td class="text-end" colspan="4"><strong>${{total_price}}</strong></td>
                </tr>
                </tbody>
            </table>
            <a href="{% url 'products:checkout' %}" class="btn btn-success">Order checkout</a>
        </div>
        {% else %}
            <div class="alert alert-info" role="alert">
                Your cart is empty
            </div>
        {% endif %}
    </div>
{% endblock %}

backend/products/templates/checkout.html
{% extends 'base.html' %}

{% block content %}

    <h2>Order checkout</h2>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Complete order" class="btn btn-primary">
    </form>
{% endblock %}

backend/products/templates/index.html
{% extends 'base.html' %}
{% load math_filters %}
{% block content %}

<div class='container'>
    <h1>Каталог Товарів</h1>
    <div class="row row-cols-1 row-cols-md-3 g-4">

            {% for product in products %}
                <div class="col">
                    <div class="card h-100 shadow-sm">
                        <img src="{{product.image_path|default:'https://assets.turbologo.com/blog/en/2021/09/10094210/product-photo-1.png'}}"
                             alt="{{product.name}}"
                             class="card-img-top">

                    <div class="card-body">
                        {% if not product.available %}
                            <span class="text-secondary">Not available</span>
                        {% else %}
                            <h5 class="card-title">{{product.name}</h5>
                        {% endif %}
                    </div>

                    <div class="product-rating">
                        {% for i in "12345" %}
                            {% if forloop.counter < products.rating %}
                                <i class="bi bi-star-fill text-warning"></i>
                            {% else %}
                                <i class="bi bi-star text-muted"></i>
                            {% endif %}
                        {% endfor %}

                    </div>
                        {% if product.discount %}
                            <span class="text-success">
                                {{ product.price|calculate_discount:product.discount }}
                            </span>
                            <span class="text-muted text-decoration-line-through">
                                {{product.price }}
                            </span>
                        {% else %}
                            <span class="text-success">
                                {{ product.price }}
                            </span>
                        {% endif %}
                    </div>

                    {% if not product.available %}
                       <span class="text-muted">Not available</span>
                    {% endif %}

                    <a href="{% url 'products:product_details' product.id %}" class="btn-primary">Details</a>
                    <a href="{% url 'products:cart_add' product.id %}" class="btn-primary">Add to your cart</a>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

backend/products/templates/product_details.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-md-6">
            <img src="{{product.image_path|default:'https://assets.turbologo.com/blog/en/2021/09/10094210/product-photo-1.png'}}">
        </div>
        <div class="col-md-6 mt-5">
            <h5>{{ product.name }}</h5>
            <p>{{ product.description }}</p>

        <div class="product-rating">
            {% for i in "12345" %}
                {% if forloop.counter < products.rating %}
                    <i class="bi bi-star-fill text-warning"></i>
                {% else %}
                    <i class="bi bi-star text-muted"></i>
                {% endif %}
            {% endfor %}
        </div>

            {% if product.discount %}
                <span class="text-success">
                    {{ product.price|calculate_discount:product.discount }}
                </span>
                <span class="text-muted text-decoration-line-through">
                    {{product.price }}
                </span>
            {% else %}
                <span class="text-success">
                    {{ product.price }}
                </span>
            {% endif %}
            <h5>Nomenclature:{{product.nomenclature}}</h5>

            {% if not product.available %}
                <span class="text-secondary">Not available</span>
            {% else %}
                <span class="text-secondary">Available</span>
            {% endif %}
            <a class="btn btn-primary" href="{% url 'product_details' product.id %}">More</a>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            {% if product.description %}
                <p>{{product.description}}</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}